version: '3.8'
services:
  db:
    container_name: finit_postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=finit
      - POSTGRES_USER=finit_user
      - POSTGRES_PASSWORD=1111

volumes:
  data: {}
